language: cpp
sudo: false
addons:
  apt:
    packages:
    - g++-7
    - clang-5.0
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - libgtk-3-dev
    - freeglut3-dev
    sources:
    - ubuntu-toolchain-r-test
before_script:
- git clone https://github.com/sfml/sfml && cd sfml
- git checkout tags/2.5.0
- mkdir build && cd build && cmake .. -G"$GENERATOR" $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=../install
- cmake --build . --target install
- cd ../..

script:
- mkdir build && cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -G"$GENERATOR" $CMAKE_FLAGS -DSFML_ROOT=../sfml/install -DCMAKE_INSTALL_PREFIX=../install
- cmake --build . --target install --config Release
- cmake --build . --target package --config Release

matrix:
  fast_finish: true
  include:
  - os: linux
    compiler: gcc
    env:
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/g++-7"
    - MATRIX_EVAL="CC=gcc-7 && GXX=g++-7"
  - os: linux
    compiler: clang
    env:
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
  - os: osx
    osx_image: xcode9
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DSFML_BUILD_FRAMEWORKS=TRUE -DSFML_MISC_INSTALL_PREFIX=../install -DSFML_DEPENDENCIES_INSTALL_PREFIX=../install"
  - os: windows
    env:
    - GENERATOR="Visual Studio 15 2017 Win64"
    - CMAKE_FLAGS=""
    
before_install:
    - eval "${MATRIX_EVAL}"
    
